#!/bin/bash
# /etc/hotplug/usb/matrix_vision.config
#
# Sets up newly plugged in mvBlueFOX USB camera so that only members of the
# group

GROUP=usb

# can access it from user space. (Replace users with the name of the
# group you want to have access to the cameras.)
#

LOGGER=`which logger`
if [ x$LOGGER == x ]; then
	LOGGER=/bin/logger
fi
if ! [ -x $LOGGER ]; then
    LOGGER=/usr/bin/logger
fi

if [ "${ACTION}" = "add" ] && [ -f "${DEVICE}" ]
then
	if [ -x $LOGGER ]; then
		$LOGGER -t $0 "making device node ${DEVICE} accessible to the group ${GROUP}"
	fi
    chmod o-rwx "${DEVICE}"
    chgrp "${GROUP}" "${DEVICE}"
    chmod g+rw "${DEVICE}"
fi

